name: toggl-linker
version: 0.1.0
summary: Toggl Linker
description: Links Toggl and e.g. Redmine to book from Toggl to Redmine Issues

confinement: strict
base: core18
grade: stable

slots:
  dbus-toggl-linker: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: io.enoy.toggl_linker # adjust accordingly to your app name and
    
apps:
  toggl-linker:
    command: toggl_linker
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-toggl-linker
parts:
  toggl-linker:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
